export default {
  login: "gogadev",
  id: 56350554,
  node_id: "MDQ6VXNlcjU2MzUwNTU0",
  avatar_url: "https://avatars3.githubusercontent.com/u/56350554?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/gogadev",
  html_url: "https://github.com/gogadev",
  followers_url: "https://api.github.com/users/gogadev/followers",
  following_url: "https://api.github.com/users/gogadev/following{/other_user}",
  gists_url: "https://api.github.com/users/gogadev/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gogadev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gogadev/subscriptions",
  organizations_url: "https://api.github.com/users/gogadev/orgs",
  repos_url: "https://api.github.com/users/gogadev/repos",
  events_url: "https://api.github.com/users/gogadev/events{/privacy}",
  received_events_url: "https://api.github.com/users/gogadev/received_events",
  type: "User",
  site_admin: false,
  name: "Gordana Radivojevic",
  company: null,
  blog: "",
  location: "Dublin, Ireland",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 95,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2019-10-09T12:26:24Z",
  updated_at: "2020-11-04T17:58:44Z",
};
